### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by alainros** [claudegel/sinope-config#1]
Hello,
Quickly how can this be installed?
Thx

**Comment by claudegel** [comment]
Sorry it's too soon. It's a new project that I've just started. Once it is fonctionnal I'll publish it on
https://community.home-assistant.io/t/sinope-line-voltage-thermostats/17157/1003

**Comment by claudegel** [comment]
This one will be to used to configure your Sinopé devices which you can manage via my three others custom_components, sinope-gt125, sinope-1 and sinope-130
